# do this last.
PROGS = 3-lightsaber.c 
# PROGS = 2-neopix.c 
# do this third:
# PROGS = 1-rgb.c  
# do this second:
# PROGS = 1-blink.c  
# do this first.
# PROGS = 0-timing-check.c 

INC += -I../0-timing

OPT_LEVEL = -O2

RUN = 1
include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3
