
#######################################################################
# tl;dr:
#   1. make sure "make check" passes.
#   2. copy your <ckalloc.c> over.
#   3. start working through the tests.
#   4. replace all our code with yours.
#   5. profit$.
CFLAGS += -finstrument-functions
#######################################################################
# <ckalloc.c> is what you work on: copy yours over b/c we'll be
# modifying it.
#
COMMON_SRC += ckalloc_ext.c
# COMMON_SRC += ckalloc.c
# STAFF_OBJS += staff-ckalloc.o

# if you want to work on one at a time.
PROGS += tests/part1-test0-bug.c     
PROGS += tests/part1-test1-no-bug.c  
PROGS += tests/part1-test2-bug.c     
PROGS += tests/part1-test3-bug.c	
PROGS += tests/part1-test4-bug.c
PROGS += tests/part1-test5-no-bug.c
PROGS += tests/part1-test6-bugs.c
# PROGS := tests/part1-test7-bug.c
PROGS += tests/part1-test8-bugs.c

# all the tests.
# PROGS := $(wildcard tests/part1-test[0-9]*.c)

#######################################################################
# when all the tests pass with your <ckalloc.c>: swap out our code.
#
# note: easiest for isolation: just copy over.  or you could link against
# your live copies (just make sure you don't break them later b/c blast
# radius is bigger :)
#   L := /Users/sunminlee/cs240lx-26spr/labs/4-malloc+gc/2-code-leak+gc
#   COMMON_SRC += $(L)/ck-gc.c
#   COMMON_SRC += $(L)/gc-asm.S
#   COMMON_SRC += $(L)/kr-malloc.c

COMMON_SRC += kr-malloc.c
# STAFF_OBJS += staff-kr-malloc.o

COMMON_SRC += ck-gc.c
# STAFF_OBJS += staff-ck-gc.o

COMMON_SRC += gc-asm.S
# STAFF_OBJS += staff-gc-asm.o

#######################################################################

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER := my-install

# set RUN = 1 if you want the code to automatically run after building.
RUN = 1

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3

checkopt:
	@echo "going to check opt level: -O:"
	@make -s clean && make -s "OPT_LEVEL=-O" RUN=0
	@make check
	
	@echo "going to check opt level: -O2:"
	@make -s clean && make -s "OPT_LEVEL=-O2" RUN=0
	@make check

	@echo "going to check opt level: -O3:"
	@make -s clean && make -s "OPT_LEVEL=-O3" RUN=0
	@make check

	@echo "going to check opt level: -Ofast:"
	@make -s clean && make -s "OPT_LEVEL=-Ofast" RUN=0
	@make check
