# PROGS := 0-fill-screen.c
# PROGS := 1-draw-commands.c
# PROGS := 2-moving_lines.c
PROGS := 3-cat.c

COMMON_SRC := ssd1306-display-driver.c
COMMON_SRC += standard-ascii-font.c

# uncomment if you want it to automatically run.
RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install
RUN = 1

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3
# include $(CS340LX_2025_PATH)/libpi/mk/Makefile.robust
