# SUPPORT_OBJS := 


# simplest example.
# PROGS := 0-simple-derive.c

# bit more fancy
# PROGS := 1-simple-derive.c

PROGS := 2-all-derive.c
# PROGS := c-for-asm.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

# uncomment if you want it to automatically run.
RUN=1

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3

